version: '3'

services:
  douban-rss:
    image: xiaobaiya000/douban-rss:latest
    container_name: douban-rss
    ports:
      - "9150:9150"
    volumes:
      - ./config:/config
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_DIR=/config
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 